spring:
  application:
    name: bakery-management
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/bakery
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


# Optional: SpringDoc OpenAPI/Swagger settings
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

app:
  costing:
    margin:
      retail: 0.40
      wholesale: 0.20