spring:
  datasource:
    url: jdbc:h2:mem:bakerydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # Use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.bakery: DEBUG
